### ISSUE TITLE
drag'n'drop in FireFox

### ISSUE THREAD

**Issue by thohoh** [500tech/angular2-tree-component#117]
Doesn't work.

FF v50.0.2
tree v2.4.0
lodash v4.17.2

**Comment by adamkleingit** [comment]
True, but very strange. FF should support HTML5 drag'n'drop completely.

**Comment by JenPeleva** [comment]
Hi, everyone. 

Any ideas whether this will be fixed anytime soon?

**Comment by thohoh** [comment]
Please give us some info on this issue.

**Comment by romanovma** [comment]
Cannot make a pull request(no permission?) but the fix is pretty easy. According to http://stackoverflow.com/questions/19055264/why-doesnt-html5-drag-and-drop-work-in-firefox we have to set data for Firefox drag and drop to work. So inside `tree-drag.directive.ts` should change 
```
@HostListener('dragstart') onDragStart() {
    setTimeout(() => this.treeDraggedElement.set(this.draggedElement), 30);
  }
```
to
```
  @HostListener('dragstart', ['$event']) onDragStart(ev) {
    // setting the data is required by firefox
    ev.dataTransfer.setData("text/plain", ev.target.id);
    
    setTimeout(() => this.treeDraggedElement.set(this.draggedElement), 30);
  }
```
and then drag and drop works in Firefox.

**Comment by adamkleingit** [comment]
Hey,
I'll review it and hopefully merge today / tomorrow.
Thanks
