### ISSUE TITLE
Tree data with REST API Call

### ISSUE THREAD

**Issue by nitslucky** [500tech/angular2-tree-component#175]
Hi,
Is it possible to produce such kind of tree with REST API data? The first call should load all the root node, because the data-set will eventually be large and I want to 'pull in' more data from the REST API progressively as the tree branches are opened by providing the ID of the root,  like the image here:

![firstcall](https://cloud.githubusercontent.com/assets/23555070/22875617/03254f90-f1cd-11e6-9d71-7fb3fdb1e56d.PNG)
And then children should be loaded with another call to REST API when i click on plus icon for example the image given below:
![getchildren](https://cloud.githubusercontent.com/assets/23555070/22875632/14a933da-f1cd-11e6-81a8-df534fac1a5c.PNG)
Thank you

**Comment by adamkleingit** [comment]
Yes, using getChildren option.
I added a section about it in readme:
https://angular2-tree.readme.io/v2.8.0/docs/async-data-1

**Comment by papagei9** [comment]
I'm not able to create the TreeNode object so that it is displayed.
What Am I doing wrong?

This code is inside of getChildren():

`new TreeNode({id: a.id, name: a.name, hasChildren: a.childAddressIds.length != 0}, node, this.tree.treeModel, i);`

Please provide an example how the returned data for getChildren should look like.
