### ISSUE TITLE
tree.treeModel.roots returns []

### ISSUE THREAD

**Issue by ciesielskico** [500tech/angular2-tree-component#58]
I want to collapse, expand roots after initialization.

I have initialized a tree with 1 root, which has several children.
I have defined the tree as a ViewChild, and after `console.logging the tree` I can see in the console, that roots in treeModel is an array of length 1. But after console.logging `tree.treeModel.roots` I get empty array.

**Comment by adamkleingit** [comment]
When are you doing console.log?

Have you tried in ngAfterViewInit ?
ngAfterViewInit() {
  this.expandRoots()
}

Or in `onInitialized` callback:
<Tree (onInitialized)="expandRoots()"></Tree>

By the way, you can use the 'isExpanded' field for initial expand or collapse of nodes.

**Comment by ciesielskico** [comment]
I'm debugging this way

```
ngAfterViewInit() {
        console.log(this.reportsTree.treeModel);
        console.log(this.reportsTree.treeModel.roots);
    }
```

It seems like the getter for roots in treeModel is buggy, since the first one prints the treeModel with roots array of length 1, but the second log prints an empty array `[]`

![screenshot from 2016-09-27 09-03-36](https://cloud.githubusercontent.com/assets/17651898/18863416/77c00c7c-8491-11e6-879d-52927cb6d000.png)

**Comment by adamkleingit** [comment]
Can you try using the (onInitialized) event instead of ngAfterViewInit?

BTW, the getter is fine. By the time you check the treeModel in the console
the roots are already there.


-- 
- Adam Klein <http://il.linkedin.com/in/adamklein500>
- CTO @ 500Tech.com <http://500tech.com/>
- AngularJS, ReactJS, NodeJS
- Development, consulting, training and public speaking
- (+972) 52 747 5633

**Comment by ciesielskico** [comment]
html
```
<div class="report-tree-container">

    <Tree #reportsTree 
        [nodes]="reports" 
        (onInitialized)="onTreeInitialized($event)"
        (onActiveChanged)="onActiveChanged($event)">
    </Tree>

</div>
```

ts
```
@ViewChild('reportsTree') reportsTree: TreeComponent;
@Input() reports: ReportTreeNode[];

onTreeInitialized() {
        console.log(this.reportsTree.treeModel);
        console.log(this.reportsTree.treeModel.roots);
    }

export interface ReportTreeNode {
    name: string;

    id?: number;
    children?: ReportTreeNode[];
}
```

Same result as above

**Comment by adamkleingit** [comment]
I'm assuming you initialize reports with an empty array, and only later
initialize it with data?
You have 3 options:

   1. Use *ngIf to show tree only if reports has data
   2. Initialize reports with null instead of empty array.
   3. Use onUpdateData event instead of onInitialized (notice that every
   time you update the pointer to reports this event will fire)


-- 
- Adam Klein <http://il.linkedin.com/in/adamklein500>
- CTO @ 500Tech.com <http://500tech.com/>
- AngularJS, ReactJS, NodeJS
- Development, consulting, training and public speaking
- (+972) 52 747 5633

**Comment by ciesielskico** [comment]
`reports` is initialized by parent component with `async` pipe.

```
<app-report-list [reports]="reports | async" (select)="selectReport($event)">
</app-report-list>
```

Using `onUpdateData` instead of `onInitialized` fixed the issue, makes sense! Thanks!
